repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
        types: [file, python]
      - id: trailing-whitespace
        types: [file, python]
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=4096]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 745be0411e3c150e246d527e531e5a221b8c3462  # v0.15.19
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
